name: Integração Contínua

on: push

jobs:
  executa_pytest:
    runs-on: macos-latest
    steps: 
      - name: Action Checkout
        uses: actions/checkout@v2


      - name: Instala o conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-activate-base: true
          activate-environment: ""
    
      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executa o black na src
        run: black --check src
      
      - name: Executa o black na app
        run: black --check app

      - name: Executa o pytest
        run: pytest